# Generated by Django 2.2.4 on 2019-08-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launches',
            name='details',
            field=models.CharField(max_length=1000),
        ),
    ]
