# Generated by Django 2.2.4 on 2019-08-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0005_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rocket_number', models.IntegerField(default=0)),
                ('active', models.CharField(blank=True, max_length=10, null=True)),
                ('cost_per_launch', models.IntegerField(default=0)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('rocket_name', models.CharField(blank=True, max_length=200, null=True)),
                ('first_flight', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('wikipedia', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
