# Generated by Django 2.2.4 on 2019-08-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0006_rocket'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocket',
            name='rocket_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
