# Generated by Django 2.2.4 on 2019-08-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0003_auto_20190816_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=10)),
                ('mission_id', models.CharField(max_length=10)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('wikipedia', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
