# Generated by Django 2.2.4 on 2019-08-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0004_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_serial', models.CharField(max_length=25)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('mission_name', models.CharField(max_length=25)),
                ('mission_flight', models.IntegerField(default=0)),
                ('details', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
